### ISSUE TITLE
Error Synthesize How can I resolve this error?

### ISSUE THREAD

**Issue by usasho** [r9y9/nnsvs#74]
[2022-03-07 06:21:16,448][nnsvs][INFO] - Processes 1 utterances...
  0%|                                                        | 0/1 [00:01<?, ?it/s]
Error executing job with overrides: ['question_path=jp.hed', 'timelag=defaults', 'duration=defaults', 'acoustic=defaults', 'timelag.checkpoint=exp/sho/timelag/best_loss.pth', 'timelag.in_scaler_path=dump/sho/norm/in_timelag_scaler.joblib', 'timelag.out_scaler_path=dump/sho/norm/out_timelag_scaler.joblib', 'timelag.model_yaml=exp/sho/timelag/model.yaml', 'duration.checkpoint=exp/sho/duration/best_loss.pth', 'duration.in_scaler_path=dump/sho/norm/in_duration_scaler.joblib', 'duration.out_scaler_path=dump/sho/norm/out_duration_scaler.joblib', 'duration.model_yaml=exp/sho/duration/model.yaml', 'acoustic.checkpoint=exp/sho/acoustic/best_loss.pth', 'acoustic.in_scaler_path=dump/sho/norm/in_acoustic_scaler.joblib', 'acoustic.out_scaler_path=dump/sho/norm/out_acoustic_scaler.joblib', 'acoustic.model_yaml=exp/sho/acoustic/model.yaml', 'utt_list=./data/list/dataset.list', 'in_dir=./data/synthes/', 'out_dir=exp/sho/synthesis/utt_list/best_loss/label_phone_score', 'ground_truth_duration=false']
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nnsvs-0.0.1-py3.8.egg/nnsvs/bin/synthesis.py", line 224, in my_app
    wav = synthesis(
  File "/usr/local/lib/python3.8/dist-packages/nnsvs-0.0.1-py3.8.egg/nnsvs/bin/synthesis.py", line 122, in synthesis
    acoustic_features = predict_acoustic(
  File "/usr/local/lib/python3.8/dist-packages/nnsvs-0.0.1-py3.8.egg/nnsvs/gen.py", line 406, in predict_acoustic
    pred_acoustic = multi_stream_mlpg(
  File "/usr/local/lib/python3.8/dist-packages/nnsvs-0.0.1-py3.8.egg/nnsvs/multistream.py", line 114, in multi_stream_mlpg
    raise RuntimeError("You probably have specified wrong dimension params.")
RuntimeError: You probably have specified wrong dimension params.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by r9y9** [comment]
https://github.com/r9y9/nnsvs/blob/08fc11dde67a11d810df92d91b43ac1e50c47ac9/nnsvs/multistream.py#L113-L114

Please check the error message.

**Comment by usasho** [comment]
stream_sizes: [180, 3, 1, 15]
has_dynamic_features: [True, True, False, True] 

Error

stream_sizes: [180, 3, 1, 3]
Error

I don't know which parameter is correct because the stream size is unknown
I did it with the default value, but I get an error

**Comment by usasho** [comment]
I'm sorry
Did not add vibrato to StreamSize
I checked the operation

**Comment by r9y9** [comment]
I see. I'll share you my config for vibrato modeling. Please hold on.

**Comment by r9y9** [comment]
This is an example of `conf/train/acoustic/model/acoustic_conv.yaml` for testing vibrato modeling with #73 

```
# @package _group_
# (mgc, lf0, vuv, bap, vib)
stream_sizes: [180, 3, 1, 15, 6]
has_dynamic_features: [true, true, false, true, true]
num_windows: 3
# If None, automatically set based on stream sizes
stream_weights:

netG:
  _target_: nnsvs.model.Conv1dResnet
  in_dim: 348
  out_dim: 205
  hidden_dim: 128
  num_layers: 6
  dropout: 0.1
```

NOTE: `in_dim` may differ depending on what hed file you use.
